yamlversion: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: financial-cents-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: financial-cents-tracker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - financial-cents-network

  redis:
    image: redis:7-alpine
    container_name: financial-cents-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - financial-cents-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: financial-cents-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/financial-cents-tracker?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - financial-cents-network

volumes:
  mongodb_data:
  redis_data:

networks:
  financial-cents-network:
    driver: bridge